# Generated by Django 3.2.18 on 2023-07-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='valum',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='education',
            name='end_data',
        ),
        migrations.AlterField(
            model_name='education',
            name='start_data',
            field=models.DateField(),
        ),
    ]
