# Generated by Django 3.2.18 on 2023-07-11 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
