# Generated by Django 3.2.18 on 2023-07-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_fact_service_socialmedia_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fact',
        ),
    ]
