# Generated by Django 3.2.18 on 2023-07-13 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_auto_20230713_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='created_on',
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(1900)]),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(1900)]),
        ),
        migrations.AlterField(
            model_name='education',
            name='university_name',
            field=models.TextField(max_length=70),
        ),
    ]
