# Generated by Django 3.2.18 on 2023-07-16 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0019_remove_experience_compani_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.TextField(max_length=40)),
                ('program_name', models.TextField(max_length=40)),
                ('cours_name', models.TextField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='languages',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='addres',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='end_data',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='job_possition',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_data',
        ),
        migrations.AddField(
            model_name='experience',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(1900)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='position_name',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(1900)]),
            preserve_default=False,
        ),
    ]
