# Generated by Django 3.2.18 on 2023-07-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0020_auto_20230716_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='cours_name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='courses',
            name='program',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='courses',
            name='program_name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_name',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
