# Generated by Django 3.2.18 on 2023-07-21 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0023_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
