# Generated by Django 3.2.18 on 2023-07-21 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0025_testimonial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonial',
            new_name='Testimonials',
        ),
    ]
