# Generated by Django 3.2.18 on 2023-07-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0026_rename_testimonial_testimonials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonials',
        ),
    ]
