# Generated by Django 3.2.18 on 2023-07-25 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0028_personalinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personalinfo',
        ),
    ]
